name: Buzzer-CI
run-name: Running Buzzer tests.
on: [push, pull_request, workflow_dispatch]
jobs:
  Buzzer-CI:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Clang
      uses: egor-tensin/setup-clang@v1
      with:
        version: 17
        platform: x64
    - name: Check Buzzer tests
      run: |
           bazel build //...
           bazel test //...
      env:
       CC:   clang
       CXX:  clang++
    - name: Package
      run: tar cvzf bazel-bin.tgz bazel-bin
    - name: Upload the package
      uses: actions/upload-artifact@v4
      with:
        name: bazel-bin
        path: bazel-bin.tgz
